### ISSUE TITLE
Propostal: using cmd element

### ISSUE THREAD

**Issue by junaruga** [sclorg/rhscl-rebuild-recipes#17]
I want to suggest below `packages - package - cmd` element to the recipe file.
The purpose is sometimes when I need to add bootstrap macro in a spec file, but can not update it soon to the repository for some reasons. Please look at below sample.

```
rh-ror50:
...
  packages:
    - rh-ror50:
        macros:
          install_scl: 0
    - rubygem-rspec
    - rubygem-rspec-core:
        replaced_macros:
          need_bootstrap_set: 1
...
    - rubygem-flexmock:
       # Instead of bootstrap macro. It is manually boostrap.
        cmd:
          - "sed -i '/^BuildRequires.*rubygem(rspec)$/ s/^/#/' rubygem-flexmock.spec"
          - "sed -i '/^%check$/,/^popd$/ s/^/#/' rubygem-flexmock.spec"
...
    - rubygem-flexmock
```

`cmd` element should not be used if we can use `macros` or `replaced_macros` instead of that.
Writing `rubygem-flexmock.spec` in the `cmd` element is not simple way.
But there is a benefit that we can write the command lines directly to the recipe file after we would succeed the command actually manually.

Right now below kind of hack is needed for the build config file of RPM List Builder to enable bootstrap.
This config file intends to be created for a unit of build environment.
Ideally bootstrap information should be managed in the recipe file with `bootstrap` macros rather than the build config file.
https://github.com/junaruga/rpm-list-builder/commit/c587c54c5ff6bb0579088db8c74734a97c48c48d

How do you think?
Can you accept this proposal?

Thanks.

**Comment by junaruga** [comment]
it has been implemented for RPM List Builder.
https://github.com/sclorg/rpm-list-builder/issues/20

**Comment by ppisar** [comment]
On Tue, Jul 25, 2017 at 09:19:11AM -0700, Jun Aruga wrote:
> it has been implemented for RPM List Builder.
> https://github.com/sclorg/rpm-list-builder/issues/20
> 
From my "patch command" use case point of view,I have several questions:

What does happen if the commmand does not exist on system? Shouldn't a build
recipe declare its dependency on a package that provides the command?  Is the
command passed to a shell (what shell, how to escape shell metacharaters?) or
executed directly? What working directory is used when executing the command?
Where can I get files or standard input for the command (patch command needs
them)? All the answers should be documented in the recipe format
specification.

-- Petr

**Comment by junaruga** [comment]
@ppisar thanks for the question.

> What does happen if the command does not exist on system?

For example below case, if a package `perl`'s `command_2` is failed, RPM List Builder stops in the position of the package `perl`,  the packages after `per` such as  `perl-Pod-Usage` does not run.
In that case, you can run from `perl` again using resume command option (`--resume RESUME_NUMBER`).

It is similar with `.travis.yml` or `sh -e`, if the command fails with error exist status (not zero), RPM List Builder stops.

```
perl516:
  packages:
    - perl516:
      cmd:
        - |
          command_1
    - perl:
      cmd:
        - |
          command_2
    - perl-Pod-Usage
    ..
```

> Shouldn't a build recipe declare its dependency on a package that provides the command?

You can declare it as you like.
You can set environment variable for `rpmlb` command.
You can also use environment variables in the `cmd` element of the recipe file.

```
$ PATH="${PATH}: /your/command/path/bin" rpmlb .. RECIPE_FILE COLLECTION_ID
```

> Is the command passed to a shell (what shell, how to escape shell metacharaters?) or executed directly

The command is run as a child process. It is like a `bash command` rather than `exec command`.
But you can use current environment's environment variables for the command.

In case of Linux maybe the shell is Linux bash (=sh). It may depend on the platform OS.
It is Python's `subprocess` module's specification.

But I suppose in case of your `perl.yml`'s "patch command" use case, using `replaced_macros` or `macros` element in the recipe file is good enough for you. You may not have to use the `cmd` element.

> how to escape shell metacharaters?

So far you do not have to escape shell meta characters.
If you use YAML block style format "|" which you have already been using,  you do not have to consider YAML meta characters too.

> What working directory is used when executing the command?

`/temp_directory/rpmlb-<random-string-8-characters>`is used such as `/tmp/rpmlb-zzxuqzmo.

But you can specify the working directory by command option `-w, --work-directory WORK_DIRECTORY`. See `rpmlb --help` for detail.

> Where can I get files or standard input for the command (patch command needs them)?

You can use your file, just set file in the recipe file.
You can not use standard input for `rpmlb` command.
If you want to use `patch` command, the solution may be using here document.

```
  packages:
    - perl516:
        patch: |
          --- a/macro-build
          +++ b/macro-build
          @@ -1,7 +1,7 @@
           %__perl %_scl_root/usr/bin/perl
           %__perl_provides /usr/lib/rpm/perl.prov.stack
           %__perl_requires /usr/lib/rpm/perl.req.stack
          -#%%perl_bootstrap 1
          +%perl_bootstrap 1
```

Can be changed to

```
  packages:
    - perl516:
        cmd: |
          patch <<EOF
--- a/macro-build
+++ b/macro-build
@@ -1,7 +1,7 @@
%__perl %_scl_root/usr/bin/perl
%__perl_provides /usr/lib/rpm/perl.prov.stack
%__perl_requires /usr/lib/rpm/perl.req.stack
-#%%perl_bootstrap 1
+%perl_bootstrap 1
EOF
```

But your case below is ideal setting after editing your the RPM spec file.

```
  packages:
    - perl516:
        replaced_macros:
           perl_bootstrap 1
```

or

```
  packages:
    - perl516:
        cmd:
          - sed -i 's/#%%perl_bootstrap 1/%perl_bootstrap 1/'
```

> All the answers should be documented in the recipe format specification.

Yes that makes sense.
RPM List Builder has Users Guide document.
If those does not exist in the document, they should be documented in this document.
https://github.com/sclorg/rpm-list-builder/blob/master/docs/users_guide.md
