### ISSUE TITLE
Syntax for bconds

### ISSUE THREAD

**Issue by hroncok** [sclorg/rhscl-rebuild-recipes#25]
The recipe format should allow to turn off/on any [bcond conditionals](http://rpm.org/user_doc/conditional_builds.html). I suggest the following syntax:

```yaml
python38:
  name: Python 3.8
  packages:
    - python38
    - python:
        without: 
          - rewheel
    - python-setuptools:
        with: 
          - whatnot
```
